service: nestjs-typescript-challenge

frameworkVersion: "3"

useDotenv: true

package:
  individually: true
  exclude:
  - '**/test/**'
  - '**/*.spec.ts'
  - '**/*.e2e.ts'
  - '**/e2e/**'
  - '**/*.map'
  - '**/docs/**'
  - '**/*.md'
  - 'node_modules/**/test/**'
  - 'node_modules/**/*.e2e.ts'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 29 # optional, in seconds, default is 6
  stage: dev
  region: us-east-2
  environment: 
    PORT: ${env:PORT}
    JWT_SECRET: ${env:JWT_SECRET}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_DATABASE: ${env:DB_DATABASE}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}

custom:
  optimize:
    external: ['swagger-ui-dist']